Logging: 
  IncludeScopes: false
  Debug:
    LogLevel: 
      Default: Information
  Console:
    LogLevel: 
      Default: Information
eureka:
  client:
    serviceUrl: http://localhost:8761/eureka/
    validate_certificates: false
security:
  oauth2:
    client:
      validate_certificates: false
management: 
  endpoints: 
    path: /cloudfoundryapplication
    cloudfoundry: 
      validateCertificates: false